### PR TITLE
add terrain info msgs

### PR DESCRIPTION
**Pull request by chaofiber**
added msgs for terrain information and will come with trajectory bag file. Gridmap is implemented in another way.

### CODE REVIEW

**Comment by mbjelonic** [comment]
@chaofiber are these the only changes? What about the smart initialization and the guide in the readme?

**Comment by chaofiber** [comment]
@mbjelonic

**Comment by chaofiber** [comment]
> @chaofiber are these the only changes? What about the smart initialization and the guide in the readme?

This is just for xpp, am still working on the towr code

**Comment by mbjelonic** [comment]
@chaofiber ah yes. Sorry, I thought this is the PR in towr.

**Pull request closed without merging**
